# Generated by Django 4.0.8 on 2023-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inside_room',
            field=models.BooleanField(default=False),
        ),
    ]
